version: '3.1'

services:
  auth:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lab365_auth_service
    depends_on:
      - mongo
    ports:
      - 3001:3001
    command: npm run start auth
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
      AUTH_SERVICE_HOST: auth
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      SECRET_SALT: ${SECRET_SALT}

  tasks:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lab365_tasks_service
    depends_on:
      - mongo
      - auth
    ports:
      - 3002:3002
    command: npm run start tasks
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
      AUTH_SERVICE_HOST: auth

  mongo:
    image: mongo:7.0
    volumes:
      - db-data:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

volumes:
  db-data:
